[build]
  command = "next build"
  publish = "out"

[context.production.environment]
  NODE_VERSION = "20"

[[redirects]]
  from = "/_next/*"
  to = "/_next/:splat"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
